site_name: My Docs
nav:
  - Home: index.md
theme:
  features:
    - navigation.tabs
    - navigation.sections
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: deep orange
  font:
    text: Maven Pro
    code: Roboto Mono